"""Initial migration with all tables

Revision ID: bdb5548afc4c
Revises: 
Create Date: 2026-01-05 06:33:07.057857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdb5548afc4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logbooks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logbooks_token'))

    op.drop_table('logbooks')
    op.drop_table('roles')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_email'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_profiles_student_number'))
        batch_op.drop_index(batch_op.f('ix_student_profiles_user_id'))

    op.drop_table('student_profiles')
    with op.batch_alter_table('course_payable_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_course_payable_course_id'))
        batch_op.drop_index(batch_op.f('idx_course_payable_item'))

    op.drop_table('course_payable_items')
    with op.batch_alter_table('course_template_payable_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_display_order'))

    op.drop_table('course_template_payable_items')
    with op.batch_alter_table('payment_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_payment_allocation_line_item_id'))
        batch_op.drop_index(batch_op.f('idx_payment_allocation_payment_id'))

    op.drop_table('payment_allocations')
    with op.batch_alter_table('enrollment_line_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_line_item_enrollment_id'))
        batch_op.drop_index(batch_op.f('idx_line_item_enrollment_payable'))
        batch_op.drop_index(batch_op.f('idx_line_item_status'))

    op.drop_table('enrollment_line_items')
    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_refund_date'))
        batch_op.drop_index(batch_op.f('idx_refund_line_item_id'))
        batch_op.drop_index(batch_op.f('idx_refund_original_payment_id'))
        batch_op.drop_index(batch_op.f('idx_refund_stripe_id'))

    op.drop_table('refunds')
    with op.batch_alter_table('course_enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_enrollments_course_id'))
        batch_op.drop_index(batch_op.f('ix_course_enrollments_status'))
        batch_op.drop_index(batch_op.f('ix_course_enrollments_student_id'))

    op.drop_table('course_enrollments')
    op.drop_table('courses')
    with op.batch_alter_table('payable_item_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_is_active'))
        batch_op.drop_index(batch_op.f('idx_item_type'))

    op.drop_table('payable_item_templates')
    op.drop_table('user_has_roles')
    with op.batch_alter_table('email_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_actions_action_key'))

    op.drop_table('email_actions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_actions',
    sa.Column('action_key', sa.VARCHAR(length=100), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('available_variables', sa.TEXT(), nullable=True),
    sa.Column('template_id', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['email_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_actions_action_key'), ['action_key'], unique=1)

    op.create_table('user_has_roles',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('role_id', sa.INTEGER(), nullable=False),
    sa.Column('assigned_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('payable_item_templates',
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('base_price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('item_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('is_taxable', sa.BOOLEAN(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('is_required', sa.BOOLEAN(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payable_item_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_item_type'), ['item_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_is_active'), ['is_active'], unique=False)

    op.create_table('courses',
    sa.Column('course_template_id', sa.INTEGER(), nullable=False),
    sa.Column('course_date', sa.DATE(), nullable=False),
    sa.Column('course_time', sa.TIME(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('location', sa.VARCHAR(length=255), nullable=True),
    sa.Column('max_students', sa.INTEGER(), nullable=True),
    sa.Column('instructor1_id', sa.INTEGER(), nullable=True),
    sa.Column('instructor2_id', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['course_template_id'], ['course_templates.id'], ),
    sa.ForeignKeyConstraint(['instructor1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['instructor2_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_enrollments',
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('enrollment_date', sa.DATETIME(), nullable=False),
    sa.Column('completion_date', sa.DATETIME(), nullable=True),
    sa.Column('course_score', sa.FLOAT(), nullable=True),
    sa.Column('attendance_percentage', sa.FLOAT(), nullable=True),
    sa.Column('brings_motorcycle', sa.BOOLEAN(), nullable=True),
    sa.Column('motorcycle_make', sa.VARCHAR(length=50), nullable=True),
    sa.Column('motorcycle_model', sa.VARCHAR(length=50), nullable=True),
    sa.Column('motorcycle_year', sa.INTEGER(), nullable=True),
    sa.Column('motorcycle_license_plate', sa.VARCHAR(length=20), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_id', name='unique_student_course')
    )
    with op.batch_alter_table('course_enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_enrollments_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_enrollments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_enrollments_course_id'), ['course_id'], unique=False)

    op.create_table('refunds',
    sa.Column('original_payment_id', sa.INTEGER(), nullable=True),
    sa.Column('enrollment_line_item_id', sa.INTEGER(), nullable=False),
    sa.Column('requested_by_user_id', sa.INTEGER(), nullable=False),
    sa.Column('processed_by_user_id', sa.INTEGER(), nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('refund_method', sa.VARCHAR(length=50), nullable=True),
    sa.Column('request_date', sa.DATETIME(), nullable=False),
    sa.Column('refund_date', sa.DATETIME(), nullable=True),
    sa.Column('reason', sa.TEXT(), nullable=True),
    sa.Column('admin_notes', sa.TEXT(), nullable=True),
    sa.Column('stripe_refund_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_line_item_id'], ['enrollment_line_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['original_payment_id'], ['payments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['processed_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_refund_id')
    )
    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_refund_stripe_id'), ['stripe_refund_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_refund_original_payment_id'), ['original_payment_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_refund_line_item_id'), ['enrollment_line_item_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_refund_date'), ['refund_date'], unique=False)

    op.create_table('enrollment_line_items',
    sa.Column('enrollment_id', sa.INTEGER(), nullable=False),
    sa.Column('course_payable_item_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('unit_price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('tax_amount', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('amount_paid', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('amount_refunded', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('admin_remarks', sa.TEXT(), nullable=True),
    sa.Column('manually_adjusted_by_user_id', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['course_payable_item_id'], ['course_payable_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['course_enrollments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manually_adjusted_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enrollment_line_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_line_item_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_line_item_enrollment_payable'), ['enrollment_id', 'course_payable_item_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_line_item_enrollment_id'), ['enrollment_id'], unique=False)

    op.create_table('payment_allocations',
    sa.Column('payment_id', sa.INTEGER(), nullable=False),
    sa.Column('enrollment_line_item_id', sa.INTEGER(), nullable=False),
    sa.Column('amount_applied', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_line_item_id'], ['enrollment_line_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id', 'enrollment_line_item_id', name=op.f('uq_payment_line_item'))
    )
    with op.batch_alter_table('payment_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_payment_allocation_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_payment_allocation_line_item_id'), ['enrollment_line_item_id'], unique=False)

    op.create_table('course_template_payable_items',
    sa.Column('course_template_id', sa.INTEGER(), nullable=False),
    sa.Column('payable_item_template_id', sa.INTEGER(), nullable=False),
    sa.Column('is_required', sa.BOOLEAN(), nullable=False),
    sa.Column('display_order', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['course_template_id'], ['course_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payable_item_template_id'], ['payable_item_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_template_id', 'payable_item_template_id', name=op.f('uq_course_template_payable_item'))
    )
    with op.batch_alter_table('course_template_payable_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_display_order'), ['display_order'], unique=False)

    op.create_table('course_payable_items',
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.Column('payable_item_template_id', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('is_required', sa.BOOLEAN(), nullable=False),
    sa.Column('is_available', sa.BOOLEAN(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payable_item_template_id'], ['payable_item_templates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_payable_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_course_payable_item'), ['course_id', 'payable_item_template_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_course_payable_course_id'), ['course_id'], unique=False)

    op.create_table('student_profiles',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('student_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('overall_score', sa.FLOAT(), nullable=True),
    sa.Column('grade_level', sa.VARCHAR(length=20), nullable=True),
    sa.Column('emergency_contact_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('emergency_contact_phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_profiles_user_id'), ['user_id'], unique=1)
        batch_op.create_index(batch_op.f('ix_student_profiles_student_number'), ['student_number'], unique=1)

    op.create_table('password_reset_tokens',
    sa.Column('token', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('is_used', sa.BOOLEAN(), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('used_at', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token'), ['token'], unique=1)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_email'), ['email'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('logbooks',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('token', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('last_updated', sa.DATETIME(), nullable=False),
    sa.Column('has_logged_out', sa.BOOLEAN(), nullable=False),
    sa.Column('timed_out', sa.BOOLEAN(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('logbooks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logbooks_token'), ['token'], unique=1)

    # ### end Alembic commands ###
